// djangostarter/static/js/components/HelloWorld.jsx
import React from 'react';
import PropTypes from 'prop-types';

const HelloWorld = ({ msg }) => (
  <div className="flex items-center justify-center h-screen">
    <h1 className="text-blue text-5xl">{msg}</h1>
  </div>
);

HelloWorld.defaultProps = {
  msg: 'Hello World!'
};

HelloWorld.propTypes = {
  msg: PropTypes.string
};

export default HelloWorld;

// djangostarter/static/js/components/HelloWorld.vue
<template>
  <div class="flex items-center justify-center h-screen">
    <h1 class="text-blue text-5xl">{{ msg }}</h1>
  </div>
</template>`

<script>
export default {
  name: 'HelloWorld',
  props: {
    msg: String
  }
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped lang="scss">
</style>
